=== ACIT4850lab/lab07/data/course.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!--
    TODO define vocabulary identification data
    PUBLIC ID  : -//vendor//vocabulary//EN
    SYSTEM ID  : http://server/path/__NAME__
-->

<!-- TODO define your own vocabulary/syntax. Example follows:  -->
<!ELEMENT term4 (timetable)>
<!ELEMENT timetable (course)+>

<!ELEMENT course (class*)>
<!ATTLIST course id CDATA #REQUIRED>

<!ELEMENT class (name, instructor, room)>
<!ATTLIST class
type (lecture|lab|tutorial) #REQUIRED
day (Monday|Tuesday|Wednesday|Thursday|Friday) #REQUIRED
start (830|930|1030|1130|1230|1330|1430|1530|1630) #REQUIRED
end (920|1020|1120|1220|1320|1420|1520|1620|1720) #REQUIRED
>
<!ELEMENT name (#PCDATA)>
<!ELEMENT instructor (#PCDATA)>
<!ELEMENT room (#PCDATA)>

=== ACIT4850lab/lab07/data/course.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
ACIT 4850
Damian Kim
Pablo Ramos

Course perspective
-->

<!DOCTYPE term4 SYSTEM 'course.dtd'>
<term4>
    <timetable>
        <course id="4850">
            <class type="tutorial" day="Thursday" start="1030" end="1220">
                <name>ACIT 4850</name>
                <instructor>James Perry</instructor>
                <room>SE12 306</room>
            </class>                   
            <class type="lecture" day="Wednesday" start="1230" end="1420">
                <name>ACIT 4850</name>
                <instructor>James Perry</instructor>
                <room>SE12 306</room>
            </class>                           
        </course>
    </timetable>
</term4>
