=== ACIT4850lab/lab07/data/timetable.xsd
<?xml version="1.0"?>
<!--
Developed by:

Damian Kim
Pablo Ramos

Timetable schema for ACIT 4850 lab 9

-->
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    
    <!-- time is a 4 digit time -->
    <xs:simpleType name="Ttime">
        <xs:restriction base="xs:integer">
            <xs:pattern value="[0-2][0-9][0-5][0-9]"/>
        </xs:restriction>
    </xs:simpleType>
    
    <!-- course: holds course type information-->
    <xs:simpleType name="Tcourse">
        <xs:restriction base="xs:string">
            <xs:enumeration value="lecture"/>
            <xs:enumeration value="lab"/>
            <xs:enumeration value="tutorial"/>
        </xs:restriction>
    </xs:simpleType>
  
    <!-- day: days of a week -->
    <xs:simpleType name="Tday">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Monday"/>
            <xs:enumeration value="Tuesday"/>
            <xs:enumeration value="Wednesday"/>
            <xs:enumeration value="Thursday"/>
            <xs:enumeration value="Friday"/>
        </xs:restriction>
    </xs:simpleType>
   
   <!-- timetable: holds differents perspetives of the timetable -->
    <xs:element name="timetable">
        <xs:complexType>
            <xs:choice>
                <xs:element name="course" type="Tcourseid"/>
                <xs:element name="period" type="Tperiod"/>
                <xs:element name="day" type="Tday1"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
	
    <!-- courseid: open id -->    
    <xs:complexType name="Tcourseid">
        <xs:sequence>
            <xs:element name="booking" type="Tbooking" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>
	
    <!-- period: holds period information -->        
    <xs:complexType name="Tperiod">
        <xs:sequence>
            <xs:element name="booking" type="Tbooking" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="start" type="Ttime" use="required"/>
        <xs:attribute name="end" type="Ttime" use="required"/>
    </xs:complexType>
    
    <!-- day1: for specific day property-->
    <xs:complexType name="Tday1">
        <xs:sequence>
            <xs:element name="booking" type="Tbooking" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="day" type="Tday" use="required"/>
    </xs:complexType>
	
    <!-- booking: holds booking information -->        
    <xs:complexType name="Tbooking">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="instructor" type="xs:string"/>
            <xs:element name="room" type="xs:string"/>
            <xs:element name="period" type="Tperiod"  minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="type" type="Tcourse" use="required"/>
        <xs:attribute name="day" type="Tday" use="optional"/>
    </xs:complexType>
	
</xs:schema>

=== ACIT4850lab/lab07/data/Period.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
ACIT 4850
Damian Kim
Pablo Ramos

Period perspective
-->
<?xml-stylesheet type='text/xsl' href='Period.xsl'?>
<timetable xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="timetable.xsd">
<period start="1030" end="1220">
    <booking type="lab" day="Tuesday">
        <name>ACIT 4620</name>
        <instructor>Bethany Edmunds</instructor>
        <room>SE12 306</room>                   
    </booking>
    <booking type="lab" day="Wednesday">
        <name>ACIT 4660</name>
        <instructor>Steve Fabzinsk</instructor>
        <room>SE12 306</room>
    </booking>
    <booking type="lab" day="Thursday">
        <name>ACIT 4850</name>
        <instructor>James Perry</instructor>
        <room>SE12 320</room>
    </booking>         
</period>
</timetable>
